# Generated by Django 4.0.4 on 2023-01-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('writter', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('download_number', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('photo', models.FileField(upload_to='website/bookphotos/')),
                ('file', models.FileField(upload_to='website/bookfiles/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('login_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyed', models.BooleanField(default=False)),
                ('buy_date', models.DateField()),
                ('book_isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('comment_date', models.DateField()),
                ('book_isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productphoto',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
        migrations.AddField(
            model_name='user',
            name='my_books',
            field=models.ManyToManyField(through='website.UserCart', to='website.book'),
        ),
    ]
